logFilters:
  - code: YN0002
    level: discard
  - code: YN0005
    level: discard
  - code: YN0007
    level: discard
  - code: YN0032
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
