name: Lint, type check, and test
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run eslint
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
  tsc:
    runs-on: ubuntu-latest
    name: Check typescript
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm ci
      - run: npx tsc
  test:
    runs-on: ubuntu-latest
    name: Run tests
    needs: [lint, tsc] # ensure tests are run only after eslint and tsc pass
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: CYPRESS_INSTALL_BINARY=0 PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci
      - run: npm run build
      - run: npm test
